/**
 * Image generation using Pollinations API.
 *
 * Pollinations provides free AI image generation via a simple URL-based API.
 * Images are generated by accessing: https://image.pollinations.ai/prompt/{encoded_prompt}
 */

const fetch = require('node-fetch');

const POLLINATIONS_BASE = 'https://image.pollinations.ai/prompt';

/**
 * Generate an image from a text prompt using Pollinations API.
 *
 * @param {string} prompt - The image description prompt
 * @param {object} opts
 * @param {number} opts.width - Image width (default 1024)
 * @param {number} opts.height - Image height (default 768)
 * @param {function} opts.onLog - Logging callback
 * @returns {Promise<Buffer>} PNG image data as Buffer
 */
async function generateImage(prompt, opts = {}) {
  const { width = 1024, height = 768, onLog = () => {} } = opts;

  const encodedPrompt = encodeURIComponent(prompt);
  const url = `${POLLINATIONS_BASE}/${encodedPrompt}?width=${width}&height=${height}&nologo=true`;

  onLog(`🎨 Generating image: "${prompt.substring(0, 80)}..."`);
  onLog(`   URL: ${url.substring(0, 120)}...`);

  const response = await fetch(url, { timeout: 120000 });

  if (!response.ok) {
    throw new Error(`Pollinations API error (${response.status}): ${response.statusText}`);
  }

  const buffer = await response.buffer();
  onLog(`✅ Image generated: ${(buffer.length / 1024).toFixed(1)} KB`);

  return buffer;
}

module.exports = { generateImage };
